### ISSUE TITLE
About the Wyckoff position used in examples.nb.

### ISSUE THREAD

**Issue by hongyi-zhao** [zhangzeyingvv/MagneticTB#2]
In the [examples.nb](https://github.com/zhangzeyingvv/MagneticTB/blob/main/examples.nb), the following Wyckoff position is used:

![image](https://user-images.githubusercontent.com/11155854/155827987-15b655ed-59c4-406c-94c2-8cd6bb5003a2.png)

But this is inconsistent with the result given on [BCS](https://cryst.ehu.es/cgi-bin/cryst/programs/nph-magwplist?gnum=191.234&wpsub=1&wpmult=2&wplet=d):

![image](https://user-images.githubusercontent.com/11155854/155828096-479a78ca-13a2-428a-8b70-2a939d221bff.png)

I also noticed the similar comment about this problem [here](https://github.com/yxli8023/yxli8023.github.io/blob/main/temp/2022-02-20-MagneTB.md#%E5%B0%8F%E7%96%91%E9%97%AE):

![image](https://user-images.githubusercontent.com/11155854/155828136-d8302c6a-eb85-4c9b-8123-a86d43fcb2f5.png)

The above referenced data corresponding to the Wyckoff Positions of Group P6/mmm (No. 191) comes from [here](https://www.cryst.ehu.es/cgi-bin/cryst/programs/nph-wp-list?gnum=191):

![image](https://user-images.githubusercontent.com/11155854/155833336-ee8c0289-bc08-4b2d-8db6-6c9fcb03df47.png)

Any hints will be highly appreciated.

Regards,
HZ

**Comment by zhangzeyingvv** [comment]
MagneticTB can consider magnetic system, and the Wyckoff position of graphene is consist with BCS server. User only need to input one of the  coordinate of the Wyckoff position, MagneticTB will automatically calculate the the other equivalent Wyckoff position. Here, in "wyckoffposition -> {{{1/3, 2/3, 0}, {0, 0, 0}}}",  "{1/3, 2/3, 0}" is the coordinate of C, and {0, 0, 0} is the magnetization-direction of C (for non-magnetic materials should be always {0,0,0}). If you want to consider another Wyckoff position you should input "wyckoffposition -> {{{2/3, 1/3, 1/2}, {0, 0, 0}},{{a2,b2,c2},{m1,m2,m3}}}", where  {a2,b2,c2} and {m1,m2,m3} are coordinate and magnetization-direction of second Wyckoff position.

**Comment by hongyi-zhao** [comment]
> If you want to consider another Wyckoff position you should input "wyckoffposition -> {{{2/3, 1/3, 1/2}, {0, 0, 0}},{{a2,b2,c2},{m1,m2,m3}}}", where {a2,b2,c2} and {m1,m2,m3} are coordinate and magnetization-direction of second Wyckoff position.

Thank you for your explanation. I looked at the source code, but still couldn't find an explanation for the above usage. Perhaps it should have been explicitly pointed out/declared:

```mathematica
$ rg -A5 wyckoffposition
magtb.wl
32:  wyckoffposition->{{{2/3,1/3,0},{0,0,1/2}}},
33-  symminformation->{{"1",{{1,0,0},{0,1,0},{0,0,1}},{0,0,0},"F"}},
34-  origin={IdentityMatrix[3],{0,0,0}};
35-  basisFunctions->{"s"},
36-  debugQ->False
37-  };
--
49:  wyckoff=(OptionValue[wyckoffposition]/.{x_?InexactNumberQ:>Rationalize@Round[x,.001]});
50-  symminfo=(OptionValue[symminformation]/.{x_?InexactNumberQ:>Rationalize@Round[x,.001]});
51-  ops=symminfo[[;;,1]];
52-  Do[matrixRep[ops[[i]]]=symminfo[[i,2]],{i,Length[ops]}];
53-  Do[tran[ops[[i]]]=symminfo[[i,3]],{i,Length[ops]}];
54-  Do[timere[ops[[i]]]=symminfo[[i,4]],{i,Length[ops]}];

Usage.wl
53:wyckoffposition::usage = "Options for init"
54-symminformation::usage = "Options for init"
55-basisFunctions::usage = "Options for init"
56-symmetryset::usage = "Options for symham"
57-lattpar::usage = "Options for init"
58-
```
So, the error described [here](https://github.com/yxli8023/yxli8023.github.io/blob/main/temp/2022-02-20-MagneTB.md#%E5%B0%8F%E7%96%91%E9%97%AE) is triggered by an incorrect call of `wyckoffposition`: It provides two wyckoff positions at once, with the second regarded as the magnetization-direction:

![image](https://user-images.githubusercontent.com/11155854/155834361-80bfdd9a-289c-4990-a868-31931869cb3e.png)

**Comment by zhangzeyingvv** [comment]
Thanks, I will expand the documentation in the future. At present, you can refer to [Comput. Phys. Commun. 270, 108153 (2022)](https://www.sciencedirect.com/science/article/abs/pii/S0010465521002654) [(arXiv:2012.08871)](https://arxiv.org/abs/2105.09504) for the explanation of `wyckoffposition`.

**Comment by hongyi-zhao** [comment]
> At present, you can refer to [Comput. Phys. Commun. 270, 108153 (2022)](https://www.sciencedirect.com/science/article/abs/pii/S0010465521002654) [(arXiv:2012.08871)](https://arxiv.org/abs/2105.09504) for the explanation of `wyckoffposition`.

Thank you for your comment, I find the following description from [(arXiv:2012.08871)](https://arxiv.org/abs/2105.09504):

![image](https://user-images.githubusercontent.com/11155854/155834746-30528a79-2045-4eab-a5cb-0fd9bf040d90.png)

In https://github.com/zhangzeyingvv/MagneticTB/issues/2#issuecomment-1051719006, you said:
> Here, in "wyckoffposition -> {{{1/3, 2/3, 0}, {0, 0, 0}}}", "{1/3, 2/3, 0}" is the coordinate of C, and {0, 0, 0} is the magnetization-direction of C (for non-magnetic materials should be always {0,0,0}).

For a magnetic material, can we determine/find the magnetization-direction automatically?

**Comment by zhangzeyingvv** [comment]
You can do the symmetry analysis to check the magnetization-direction or direct look up the BCS server. However, magnetization-direction does not take part in the reduction of the Hamiltonian but works as an inspection. If you're very confident about the lattice structure and MSG number, just set all of them to `{0,0,0}` in magnetic structure, all the magnet symmetry for given MSG will be considered.

**Comment by hongyi-zhao** [comment]
> You can do the symmetry analysis to check the magnetization-direction 

If I understand correctly, the magnetization-direction will be related to some kinds of spin orbit coupling or spin polarized calculation, but not both of them simultaneously, as I've commented [here](https://github.com/goodluck1982/SpaceGroupIrep/issues/16#issue-1129422199).

> or direct look up the BCS server.

There are so many tools/utilities existed on the BCS server. Can you provide a link to this?

**Comment by zhangzeyingvv** [comment]
Magnetic Symmetry and Applications->MWYCKPOS

**Comment by hongyi-zhao** [comment]
I see, the non-zero magnetization-direction will be represented by `m_x, m_y, m_z`, as shown below:

![image](https://user-images.githubusercontent.com/11155854/155882644-512a6207-5231-40f7-96dc-8864dd321f3b.png)

But I still have the following confusion: Taking the coordinate `(x,y,z | m_x,m_y,m_z)`, shown in the above screenshot as an example, in this situation, how should I pass it to the `wyckoffposition` parameter of the `init` section defined in `MagneticTB`?

**Comment by zhangzeyingvv** [comment]
`m_x,m_y,m_z` can be arbitrary real numbers. But if it is `m_x,0,-m_x` then you should input the magnetization-direction like `1,0,-1`.

**Comment by hongyi-zhao** [comment]
Is this also the rule for `x, y, z` with the restriction of `0 =< x, y, z <= 1`?

**Comment by zhangzeyingvv** [comment]
Yes.

**Comment by hongyi-zhao** [comment]
If I understand correctly, for a specific `(x,y,z | m_x,m_y,m_z)` pattern/mode, all the different combinations of concrete `(x,y,z | m_x,m_y,m_z)` constitute a set of points for which site [symmetry groups](https://en.wikipedia.org/wiki/Symmetry_group) are conjugate [subgroups](https://en.wikipedia.org/wiki/Subgroup) of the [magnetic space group](https://en.wikipedia.org/wiki/Magnetic_space_group).

**Comment by zhangzeyingvv** [comment]
you can refer to Supplementary Material of Nature, 2017, 547, 298.
![image](https://user-images.githubusercontent.com/16720344/156165854-f442b9eb-0bf2-4b8f-a522-965da6bae1e9.png)

**Comment by hongyi-zhao** [comment]
Thank you. The paper is [here](https://www.nature.com/articles/nature23268), and the supplementary information is [here](https://static-content.springer.com/esm/art%3A10.1038%2Fnature23268/MediaObjects/41586_2017_BFnature23268_MOESM1_ESM.pdf).
