### ISSUE TITLE
For the precise determination of the parameters appeared in `Sum` of `symham` used by `bandplot`.

### ISSUE THREAD

**Issue by hongyi-zhao** [zhangzeyingvv/MagneticTB#4]
The following is an example represented in [examples.nb](https://github.com/zhangzeyingvv/MagneticTB/blob/main/examples.nb):

![image](https://user-images.githubusercontent.com/11155854/155835338-fe0aea4e-fbef-435d-9f2c-19d927226273.png)
![image](https://user-images.githubusercontent.com/11155854/155835351-774b9552-8a62-40d0-bc1b-e0f1876c92ab.png)
![image](https://user-images.githubusercontent.com/11155854/155835365-f6e0f327-a3b7-4c6f-aa98-329c2645417f.png)

As you can see, there are so many undetermined parameters here, so, what's the method used by you to determine them precisely?

Regards,
HZ

**Comment by zhangzeyingvv** [comment]
This is a toy model, we just set the parameters randomly. However, if you want to fit the DFT results, I recommend using the least-squares method.

**Comment by hongyi-zhao** [comment]
Another question: What are the currently implemented method to determine the number of adjustable parameters / degrees of freedom, and is there any way to further reduce their number?

Side remark: It seems that [`WannSymm`](https://github.com/ccao/WannSymm) is a tool that is somewhat related and complementary to this package.

**Comment by zhangzeyingvv** [comment]
The method to determine the number of parameters can be found in linear algebra which is equivalent to solve the null space of a large matrix. I don't think is it possible to reduce parameters unless the input structure has extra symmetries.

**Comment by hongyi-zhao** [comment]
I see the math behind it. Thanks again for the explanation. 

BTW, I checked the `symham` related functions defined in `MagneticTB`, as shown below: 

```shell
$ rg  -i '^[^ ]*symham\['
magtb.wl
316:unsymham[n_]:=Module[{bondends,bandind,hop,bonds,toband,nbh,hami},
347:symham[n_,OptionsPattern[]]:=Module[{conjh,h,phpmh,recR,para,sset,opset},
```
And it seems that the built-in [`NullSpace`](https://reference.wolfram.com/language/ref/NullSpace.html) command hasn't been used at all:

```shell
$ rg -i null
magtb.wl
282:   postive = Table[findeqv[bondtran[[i]]], {i, l}] /. Null -> \[Pi] ;
285:    Table[-findeqv[bondtran[[i]]], {i, l}] /. Null -> -\[Pi];
```
I'm not sure why you don't use the relevant built-in command to solve this kind of problem.

**Comment by zhangzeyingvv** [comment]
This is due to the programming details, I will try to implement it in the next version of MagneticTB.
