### ISSUE TITLE
MagneticTB在构建磁性体系哈密顿量的时候考虑了那些相互作用

### ISSUE THREAD

**Issue by Venve-X** [zhangzeyingvv/MagneticTB#5]
老师您好！我想请问下MagneticTB在构建磁性体系哈密顿量的时候考虑了那些相互作用呢？除了SOC之外，有没有考虑别的关联效应，例如海森堡或者DM相互作用呢？

**Comment by zhangzeyingvv** [comment]
MagneticTB构造的模型只对一般的单电子紧束缚哈密顿量进行对称性约束。即

$H=\sum_{ij\sigma\sigma'} t_{ij\sigma\sigma'}c_{\sigma i}^{+}c_{\sigma' j}$

其中$i,j$ 为格点和轨道指标，$\sigma, \sigma'$为自旋指标。如果关联作用不能写成上述形式，就不支持。

**Comment by Venve-X** [comment]
谢谢老师
