### ISSUE TITLE
MagneticTB能否任意指定basisfunction

### ISSUE THREAD

**Issue by Venve-X** [zhangzeyingvv/MagneticTB#6]
老师好，我希望根据DFT的计算结果拟合费米面附近的能带以建立最小模型。我往往是通过看DFT计算出费米面附近哪些轨道占据大来定出基函数的。但是在实际操作过程中会遇到“Error! Your basis(es) cannot be the rep of point group, I refuse to do this job.”的问题。怎么解决呢？

**Comment by zhangzeyingvv** [comment]
这个错误的意思就是你考虑的轨道不够 比如在立方晶系中只考虑pz轨道显然不行，因为沿着体对角线的C3会把pz变成px和py，得三个p轨道都考虑。
